server:
  port: 8600
  servlet:
    context-path: /auth

spring:
  application:
    name: @artifactId@
  profiles:
    active: dev
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: localhost:8848
        namespace: 5a8db0f6-134e-4982-8258-40d25df99408
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
  config:
    import:
      - optional:nacos:application-${spring.profiles.active}.yml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml